spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #数据源1
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.100.36:3306/daily?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(gxANzwM5Tr6Ay5q8wIyWxQ==)
        password: ENC(z8kFSfOtjUuGlOTScmQFCg==)

        #   数据源其他配置
        initialSize: 10
        minIdle: 10
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        filter:
          config:
            enabled: true
          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      second:  #数据源2
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.100.36:3306/security_test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(gxANzwM5Tr6Ay5q8wIyWxQ==)
        password: ENC(z8kFSfOtjUuGlOTScmQFCg==)
        driverClassName: com.mysql.jdbc.Driver
          #   数据源其他配置
        initialSize: 10
        minIdle: 10
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        filter:

          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      test:  #数据源3
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.100.36:3306/mybatisplus?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(gxANzwM5Tr6Ay5q8wIyWxQ==)
        password: ENC(z8kFSfOtjUuGlOTScmQFCg==)
        driverClassName: com.mysql.jdbc.Driver

  #debug 开发模式
  debug: true
  redis:
    host: 192.168.100.50
    password: qgwyadmin
    database: 5
    #连接超时时间
    timeout: 5000
  rabbitmq:
    host: 192.168.100.51
    username: admin
    password: admin
    virtual-host: my_vhost
  security:
    user:
      name: fei
      password: tmdwrn
#security登录-验证码配置
loginCode:
  expiration: 3 #登录验证码过期时间，单位 分钟
  prefix: login_code #验证码redis的key值前缀


log:
 level: debug

server:
  port: 49000

jasypt:
  encryptor:
    password: G0CvDz7oJn6
app:
  id: qgwy-eureka-client
apollo:
  meta: http://192.168.100.53:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

#apollo.cacheDir=/var/run/apollo-cache
