spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      first:  #数据源1
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.6:3306/bi_report?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
#        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(OPub1FZ3yqWpPPXBYP+b3A==)
        password: ENC(ZJf7/u+gsyNd+hFrNN3NeQIBVsEEH6mI)

        #   数据源其他配置
        initialSize: 10
        minIdle: 10
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        filter:
          config:
            enabled: true
          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      second:  #数据源2
        url: jdbc:mysql://192.168.1.6:3306/bi_report?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        #        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(OPub1FZ3yqWpPPXBYP+b3A==)
        password: ENC(ZJf7/u+gsyNd+hFrNN3NeQIBVsEEH6mI)
        driverClassName: com.mysql.jdbc.Driver
          #   数据源其他配置
        initialSize: 10
        minIdle: 10
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        filter:

          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      test:  #数据源3
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.6:3306/bi_report?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        #        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
        username: ENC(OPub1FZ3yqWpPPXBYP+b3A==)
        password: ENC(ZJf7/u+gsyNd+hFrNN3NeQIBVsEEH6mI)

  #debug 开发模式
  debug: true


log:
 level: debug

server:
  port: 49000

jasypt:
  encryptor:
    password: G0CvDz7oJn6


#apollo.cacheDir=/var/run/apollo-cache
