server:
  port: 28834
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://admin:eureka@peer2:28835/eureka/,http://admin:eureka@peer3:28836/eureka/
      #defaultZone: http://${eurekaHost}:${server.port}/eureka/
  server:
    enable-self-preservation: false
spring:
  profiles: peer1
  security:
    user:
      name: admin
      password: eureka
  application:
    name: eureka-server
---
server:
  port: 28835
spring:
  profiles: peer2
  security:
    user:
      name: admin
      password: eureka
  application:
    name: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer3:28836/eureka/
  instance:
    prefer-ip-address: false
    hostname: peer2
---
server:
  port: 28836
spring:
  profiles: peer3
  security:
    user:
      name: admin
      password: eureka
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer2:28835/eureka/