server:
  port: 18840
  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer2:28835/eureka/,http://admin:eureka@peer2:28836/eureka/
spring:
  application:
    name: ribbon-client
  profiles: 8761
---
server:
  port: 18841
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer2:28835/eureka/,http://admin:eureka@peer2:28836/eureka/
spring:
  application:
    name: ribbon-client
  profiles: 28834
  sleuth:
    #    web:
    #      client:
    #        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.100.35:9411 # 指定了 Zipkin 服务器的地址