server:
  port: 18850
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer2:28835/eureka/,http://admin:eureka@peer2:28836/eureka/
spring:
  application:
    name: feign-client
  profiles: 28834
feign:
  hystrix:
    enabled: true
