server:
  port: 18870
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:eureka@peer1:28834/eureka/,http://admin:eureka@peer2:28835/eureka/,http://admin:eureka@peer2:28836/eureka/
spring:
  application:
    name: zuul-test
  profiles: 28834

zuul:
  routes:
    feign-app:
      path: /feign/**
      serviceId: feign-client
    ribbon-app:
      path: /ribbon/**
      serviceId: ribbon-client
